name: flutter_logs
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  flutter_bloc: ^8.1.3
  rxdart: ^0.27.3
  equatable: ^2.0.3
  json_annotation: ^4.8.1
  json_to_model:
  http: 
  cupertino_icons: ^1.0.2
  meta: ^1.2.4
  device_info: ^2.0.2
  url_launcher: ^6.0.7
  connectivity: ^3.0.2
  flutter_secure_storage: ^9.0.0
  fluttertoast: ^8.2.2
  package_info: ^2.0.2
  path_provider: ^2.0.2
  shared_preferences: ^2.0.6
  checkdigit: ^0.3.1
  auto_exporter: ^1.4.8
  flutter_gen:
  

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1



flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logs/
